spring:
  application:
    name: baby-registration-service
  datasource:    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: Mysql!2019
  jpa:    generate-ddl: false    
    
server:
  port: 8072
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka
  instance:
    hostname: localhost